services:
  - type: web
    name: language-detector-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt && python -m src.train"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
